services:
  proxy-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    ports:
      - "9090:9090"
    networks:
      - proxy-network
    environment:
      - LOCAL_HOST=simple-server
      - LOCAL_PORT=4000
    depends_on:
      - simple-server

  proxy-client:
    build:
      context: .
      dockerfile: Dockerfile.client
    ports:
      - "8080:8080"
    environment:
      - SERVER_HOST=proxy-server
    depends_on:
      - proxy-server
    networks:
      - proxy-network

  simple-server:
    build:
      context: .
      dockerfile: Dockerfile.simple-server
    ports:
      - "4000:4000"
    expose:
      - "4000"
    networks:
      - proxy-network
    environment:
      - PORT=4000

networks:
  proxy-network:
    driver: bridge
